# Site settings
author: Hassan Bajwa
title: 
header-img: img/home-bg.png
email: bajwahassan3@outlook.com
copyright_name: Hassan Bajwa
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hbajwaa

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
